### ISSUE TITLE
ImportError: cannot import name 'dot3'

### ISSUE THREAD

**Issue by TacHuynh** [peter-moran/highway-lane-tracker#2]
Followed your installation instruction. But got this import package error "dot3" from filterpy.kalman.
I search the filterpy.kalman codes, only dot is supported.
Thanks for looking into this.
Tac.

(carnd-term1) EliteBook-8540w:~/highway-lane-tracker$ python find_lane.py ./data/test_videos/project_video.mp4
/home/th/anaconda3/envs/carnd-term1/lib/python3.5/site-packages/matplotlib/font_manager.py:280: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  'Matplotlib is building the font cache using fc-list. '
Traceback (most recent call last):
  File "find_lane.py", line 20, in <module>
    from windows import Window, filter_window_list, joint_sliding_window_update, window_image
  File "/home/th/highway-lane-tracker/windows.py", line 5, in <module>
    from filterpy.kalman import KalmanFilter, logpdf, dot3
ImportError: cannot import name 'dot3'
(carnd-term1)EliteBook-8540w:~/highway-lane-tracker$

**Comment by peter-moran** [comment]
Pardon the late reply, I've been on vacation.

Filterpy must have removed it before the newest version. Anyway, `dot3(a, b, c)` is equivalent to `dot(a, b).dot(c)`, so you could redefine `dot3` at the top of the file for a quick fix.

**Comment by ryanjung94** [comment]
Hi, preter-moran !

I am grateful for the data you have uploaded.

but, I have some problem.

I'm a beginner. so i don't understand your say that "Filterpy must have removed it before the newest version. Anyway, dot3(a, b, c) is equivalent to dot(a, b).dot(c), so you could redefine dot3 at the top of the file for a quick fix."

How do I modify the window.py file?

**Comment by peter-moran** [comment]
Modify the top of `window.py` so it says:

```python
from typing import List, Tuple

import numpy as np
from filterpy.common import Q_discrete_white_noise
from filterpy.kalman import KalmanFilter, logpdf
from scipy.ndimage.filters import gaussian_filter

def dot3(a, b, c):
    return dot(a, b).dot(c)
```

I have not tested this, but that is what I mean for @TacHuynh to try.
